### ISSUE TITLE
product image URL still contain pub/ folder when using pub/ as document root

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#74] opened 2018-11-28 17:17 UTC
As [recommended by the official documentation](https://devdocs.magento.com/guides/v2.2/install-gde/tutorials/change-docroot-to-pub.html) we have set the document root of our Magento 2.2.6 installation to the `pub/` folder. However, now the product images in the FACT Finder Suggest and Search results will not work.

This is because the export, when executed via Magento's cron, is unaware of the web server's DocumentRoot and thus the product image URLs will still contain the `pub/` folder.

Though I am not sure if this is may be a configuration isse on Magento's side. However, I haven't found any configuration that could be done for this case.

**Comment by a-laurowski** [comment] 2018-11-29 06:51
Hi @fritzmg 
thank You for reporting the problem. 

I will investigate this. The Nginx configuration of our testing environemnt is the same as in Magento documentation you mention, so there shouldn't be any problems with reproducing described situation

By saying that images are not work You mean that they direct to 404 when "pub" directory name is present in URL address or either image placeholders exported when feed file is generated by Cron process?

**Comment by a-laurowski** [comment] 2018-11-29 09:18
Could You please tell me If placing "pub" in the image URL cause image won't be found?
I'm asking because in our test environment whether URL address contains /pub or not, images are correctly served from server. 

http://magento2.fact-finder.de/pub/media/catalog/product/cache/6dd18fb85a59916e944c7f1f42e58a4c/m/b/mb01-blue-0.jpg

http://magento2.fact-finder.de/media/catalog/product/cache/6dd18fb85a59916e944c7f1f42e58a4c/m/b/mb01-blue-0.jpg


So if it's an issue, can You provide Your nginx configuration to let me check if something in this configuration prevent images being accesible when URL contains "pub" .
If it's an SEO problem problem, I will have to think about how to solve it comprehensively. Perhaps adding boolean flag to module configuration, which will tell the exporter to string replace "pub" with empty string could be the simpliest solution

**Comment by fritzmg** [comment] 2018-11-29 09:35
The `pub/` URL leads to 404 error of Magento.

We are using an Apache environment with Magento's default `.htaccess`. What is your `nginx` configuration? If your DocumentRoot (by that I mean nginx' equivalent of that of course 😉) is set to `pub/`, then your nginx configuration must contain a rewrite rule, to remove the `pub/` part of any request containing `pub/`.

We could also implement such an URL rewrite rule - but I'd still consider that a workaround.

**Comment by fritzmg** [comment] 2018-11-29 10:58
Even if you are using nginx, you still need some sort of configuration, to automatically rewrite any URLs containing `pub/` to remove the `pub/` part. Otherwise how would nginx know where to find the file?

**Comment by a-laurowski** [comment] 2018-11-30 10:29
Hi @fritzmg 
In Magento2 default Nginx configuration it works a little bit different. Server doesnt't cut out `pub`  from the URL. Instead of this, both of URL are available

The root is set to `$MAGE_ROOT/pub` so URL like `www.example.com/media` will be directed to `$MAGE_ROOT/pub/media` and there is nothing wrong with that.

```
root $MAGE_ROOT/pub;
```

In addition to this there is extra location directive in Nginx configuration `/pub` which add alias `$MAGE_ROOT/pub/` which means that URL like `www.example.com/pub` also will be directed to  `$MAGE_ROOT/pub/`. 

```
location /pub/ {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    alias $MAGE_ROOT/pub/;
    add_header X-Frame-Options "SAMEORIGIN";
}
```



Without this alias same URL would be directed to `$MAGE_ROOT/pub/pub` (because `root` already points to  `$MAGE_ROOT/pub` and second `pub` is taken from URL)


Despite this, I found a solution. The problem mentioned there seems to be similar as Yours
https://github.com/magento/magento2/issues/9111

**Comment by fritzmg** [comment] 2018-11-30 10:38
Yes, or rather https://github.com/magento/magento2/issues/8868

And as user reports there as well, there is probably no way to produce the correct front end URL, since the CLI cannot know the DocumentRoot of the web server: https://github.com/magento/magento2/issues/8868#issuecomment-375893064

So no final solution is available, just workarounds. The workaround we are using is simply
```
RewriteRule ^pub/(.*) $1
```
in our `.htaccess`. Which would be similar to the behavior you are experiencing in your nginx setup.

**Comment by davidverholen** [comment] 2019-04-09 21:05
there is a setting which solves exactly that problem for sitemap.xml generation: https://github.com/magento/magento2/issues/5321#issuecomment-424294957

You can put document_root_is_pub => true in env.php which tells magento that the document root is in pub. Not sure if it works out of the box for image urls but even if not you could use that to fix the url generation

**Comment by fritzmg** [comment] 2019-04-10 05:44
According to the comment, images will still have `pub/`.

**Comment by a-laurowski** [comment] 2019-07-08 04:57
I'm closing ticket as it is related to magento2, not the module itself

**Closed by a-laurowski** 2019-07-08 04:57 UTC
Labels: question

**Comment by TimPietrusky** [comment] 2020-06-10 08:58
We are facing the same issue:

- URL of Magento points to `/pub`
- We updated `app/etc/env.php` and included `'document_root_is_pub' => true`

But then comes the weird part when exporting the CSV: 

- With the nightly Cron-Export: Image URLs contain `/pub` 
- With the HTTP-Export: Image URL doesn't contain `/pub`

I'm not sure if this is a bug or a half-feature.

We are using `magento2-factfinder:1.5.1` in Magento 2.3.2 CE.

**Comment by fritzmg** [comment] 2020-06-10 09:05
> But then comes the weird part when exporting the CSV:
> 
> * With the nightly Cron-Export: Image URLs contain `/pub`
> 
> * With the HTTP-Export: Image URL doesn't contain `/pub`

That is to be expected actually.

**Comment by TimPietrusky** [comment] 2020-06-10 09:07
@fritzmg But shouldn't it be consistent so that the user is not confused?

**Comment by fritzmg** [comment] 2020-06-10 09:19
Yes it should, but it's more a Magento issue, not an issue of this module.

**Comment by TimPietrusky** [comment] 2020-06-10 09:25
This module is not working for me when I'm using the recommended settings from Magento, so from a user point of view this is an issue with this module. I would at least expect an official guideline on how this should be handled, for example like Algolia does it in their [FAQ](https://www.algolia.com/doc/integration/magento-2/troubleshooting/general-faq/?language=php#image-links-start-with-pub) (they even provide an option in their extension to remove /pub from the link before it gets indexed, which is nice to have).

**Comment by fritzmg** [comment] 2020-06-10 09:30
@TimPietrusky apparently you can configure this now: https://github.com/magento/magento2/issues/8868#issuecomment-535958665

**Comment by TimPietrusky** [comment] 2020-06-19 15:01
@fritzmg thank you, this works. I would still appreciate it if that would be at least mentioned in the README.

**Comment by TimPietrusky** [comment] 2020-07-16 15:54
In order to get this configuration into the repository, you can also add the lines into `app/etc/config.php` like this:

```php
<?php
return [

    // Those three lines are important as they define that the root of Magento is the pub folder
    'directories' => [
        'document_root_is_pub' => true
    ],

    ...
```
